spring.datasource.url= jdbc:postgresql://localhost:5432/reminderBot
spring.datasource.username= postgres
spring.datasource.password= 79825560878

spring.liquibase.change-log= classpath:liquibase/changelog-master.yml

telegram.bot.token= 7761088794:AAG2E5NiXzigH9xJOIvpnm6cVT9Xqc1delA
telegram.bot.scheduledCronExpression= 0 0/1 * * * *