spring.datasource.url= jdbc:postgresql://localhost:5432/reminderBot
spring.datasource.username= user
spring.datasource.password= 123

spring.jpa.hibernate.ddl-auto= validate

spring.liquibase.change-log= classpath:liquibase/changelog-master.yml

telegram.bot.token=
telegram.bot.scheduledCronExpression= 0 0/1 * * * *
